// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/ecommerce/front","layout":false,"id":"1"},"2":{"path":"","redirect":"category","parentId":"1","id":"2"},"3":{"path":"category","parentId":"1","id":"3"},"4":{"path":"/user","layout":false,"id":"4"},"5":{"name":"login","path":"/user/login","parentId":"4","id":"5"},"6":{"path":"/welcome","name":"welcome","icon":"smile","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"/admin","name":"admin","icon":"crown","access":"canAdmin","parentId":"ant-design-pro-layout","id":"7"},"8":{"path":"/admin","redirect":"/admin/sub-page","parentId":"7","id":"8"},"9":{"path":"/admin/sub-page","name":"sub-page","parentId":"7","id":"9"},"10":{"name":"list.table-list","icon":"table","path":"/list","parentId":"ant-design-pro-layout","id":"10"},"11":{"name":"pms","path":"/ecommerce","parentId":"ant-design-pro-layout","id":"11"},"12":{"name":"category","path":"category","parentId":"11","id":"12"},"13":{"name":"brand","path":"brand","parentId":"11","id":"13"},"14":{"name":"product","path":"product","parentId":"11","id":"14"},"15":{"name":"publish","path":"publish","parentId":"14","id":"15"},"16":{"name":"manage","path":"manage","parentId":"14","id":"16"},"17":{"name":"demo","path":"demo","parentId":"11","id":"17"},"18":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"18"},"19":{"path":"*","layout":false,"id":"19"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}},
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__ECommerceFrontLayout" */'@/layouts/ECommerceFrontLayout.jsx')),
'2': React.lazy(() => import( './EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__ECommerceFront__ShopByCategory__index" */'@/pages/ECommerceFront/ShopByCategory/index.jsx')),
'4': React.lazy(() => import( './EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'7': React.lazy(() => import( './EmptyRoute')),
'8': React.lazy(() => import( './EmptyRoute')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Admin" */'@/pages/Admin.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__TableList__index" */'@/pages/TableList/index.tsx')),
'11': React.lazy(() => import( './EmptyRoute')),
'12': React.lazy(() => import(/* webpackChunkName: "p__ProductManagement2__Category" */'@/pages/ProductManagement2/Category.jsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__ProductManagement2__Brand" */'@/pages/ProductManagement2/Brand.jsx')),
'14': React.lazy(() => import( './EmptyRoute')),
'15': React.lazy(() => import(/* webpackChunkName: "p__ProductManagement2__Product__Publish" */'@/pages/ProductManagement2/Product/Publish.jsx')),
'16': React.lazy(() => import(/* webpackChunkName: "p__ProductManagement2__Product__Manage2" */'@/pages/ProductManagement2/Product/Manage2.jsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__ProductManagement__Demo" */'@/pages/ProductManagement/Demo.jsx')),
'18': React.lazy(() => import( './EmptyRoute')),
'19': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'D:/CODING_STUDY/fontend/ecommerce_website/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'D:/CODING_STUDY/fontend/ecommerce_website/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
