// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'D:/CODING_STUDY/fontend/ecommerce_website/node_modules/.store/@ant-design+icons@4.8.0/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from 'D:/CODING_STUDY/fontend/ecommerce_website/node_modules/.store/@ant-design+icons@4.8.0/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from 'D:/CODING_STUDY/fontend/ecommerce_website/node_modules/.store/@ant-design+icons@4.8.0/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, CrownOutlined, TableOutlined };
