// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'D:/CODING_STUDY/fontend/ecommerce_website/src/pages/ECommerceFront/models/attribute';
import model_2 from 'D:/CODING_STUDY/fontend/ecommerce_website/src/pages/ECommerceFront/models/category';
import model_3 from 'D:/CODING_STUDY/fontend/ecommerce_website/src/.umi/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'ECommerceFront.attribute', model: model_1 },
model_2: { namespace: 'ECommerceFront.category', model: model_2 },
model_3: { namespace: '@@initialState', model: model_3 },
} as const
