// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'D:/CODING_STUDY/fontend/ecommerce_website/src/models/backtest';
import model_3 from 'D:/CODING_STUDY/fontend/ecommerce_website/src/pages/ECommerceFront/models/attribute';
import model_4 from 'D:/CODING_STUDY/fontend/ecommerce_website/src/pages/ECommerceFront/models/category';
import model_5 from 'D:/CODING_STUDY/fontend/ecommerce_website/src/.umi/plugin-initialState/@@initialState';
import model_2 from 'D:/CODING_STUDY/fontend/ecommerce_website/src/models/ecommerceFront';

export const models = {
model_1: { namespace: 'backtest', model: model_1 },
model_3: { namespace: 'ECommerceFront.attribute', model: model_3 },
model_4: { namespace: 'ECommerceFront.category', model: model_4 },
model_5: { namespace: '@@initialState', model: model_5 },
model_2: { namespace: 'ecommerceFront', model: model_2 },
} as const
